name: cloud_firestore_all
description: A Firebase Firestore wrapper for Flutter that wraps cloud_firestore and firebase into a single API for use on both Flutter web and mobile
version: 0.1.0+2
author: Kabir Kwatra <kabir@kwatra.me>
homepage: https://github.com/kabirkwatra/cloud_firestore_all

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mobile:
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+1

  # Web:
  firebase: ^7.1.0
